"""empty message

Revision ID: c484efd864ab
Revises: 3e0f848d4f01
Create Date: 2024-04-22 20:38:37.755300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c484efd864ab'
down_revision: Union[str, None] = '3e0f848d4f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
